### ISSUE TITLE
Which Ruby version? 

### ISSUE THREAD

**Issue by arjamizo** [trekawek/vigenere#1]
When I try to run this program, I get 
```vig.rb:103:in `-': String can't be coerced into Fixnum (TypeError)```

here ideone: http://ideone.com/CrkvyP

**Comment by trekawek** [comment]
Script has one bug resulting in the above error. Fixed in ed06412978b6e1eba7cdccb05e9a4e7889e76349. Test on Ruby 2.1.2.
